server:
  servlet:
    context-path: /


springdoc:
  packagesToScan: com.sepacyber.ipgproxy.api

spring:
  application:
    name: ipg-proxy
  profiles:
    active: dev,swagger
  redis:
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}

  cloud.stream:
    bindings:
      payment-processed-out:
        destination: ${KAFKA_IPG_PAYMENT_PROCESSED_TOPIC:ipg.payment.processed} #topic name
    kafka.streams:
      binder:
        brokers: ${KAFKA_BROKERS:localhost:9092}


      #TODO: number of partitions for each topic

  config:
    import: optional:configserver:https://sepa-cyber.com/api/production/config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST:62.171.137.149}:${MARIADB_PORT:3308}/ipg_proxy
    username: ${MARIADB_USERNAME:abraham}
    password: ${MARIADB_USERNAME:abraham}

  liquibase:
    change-log: classpath:/db/liquibase/master.xml
    user: ${MARIADB_USERNAME:abraham}
    password: ${MARIADB_USERNAME:abraham}
    enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
business:
  service:
    url: ${BUSINESS_MS_API_URL:http://localhost:3000}


application:
  ipg:
    success-response-codes:
      - "200"
      - "10004"
      - "90026"
      - "00008"
      - "00009"
      - "00002"
      - "00024"
      - "00003"
      - "00025"
      - "00022"
      - "00001"
      - "00023"
      - "00006"
      - "00028"
      - "00007"
      - "00029"
      - "00004"
      - "00026"
      - "00005"
      - "00027"
      - "00020"
      - "00019"
      - "00013"
      - "00035"
      - "00014"
      - "00011"
      - "00012"
      - "00034"
      - "00017"
      - "00018"
      - "00015"
      - "00016"
      - "00031"
      - "00010"
      - "00030"
  status:
    poll:
      schedule: '*/10 * * * * *'

config:
  sidecar:
    event-topic: config-sidecar_tenant_config_event_channel