server:
  port: 8090

business:
  service:
    url: https://microservices-business.local.sepa-cyber.com/api/v1

spring:
  cloud.stream:
    bindings:
      payment-processed-out:
        destination: ${KAFKA_IPG_PAYMENT_PROCESSED_TOPIC:ipg.payment.processed} #topic name
    kafka.streams:
      binder:
        brokers: ${KAFKA_BROKERS:odc-mqd01.local.sepa-cyber.com:9092}