server:
  port: 8080

business:
  service:
    url: https://microservices-business.local.sepa-cyber.com/api/v1

spring:
  cloud.stream:
    kafka.streams:
      binder:
        brokers: ${KAFKA_BROKERS:odc-mqd01.local.sepa-cyber.com:9092}
        #brokers: ${KAFKA_BROKERS:localhost:9092}