server:
  servlet:
    context-path: /

spring:
  application:
    name: ipg-proxy
  profiles:
    active: dev,swagger

  config:
    import: optional:configserver:https://sepa-cyber.com/api/production/config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ipg_proxy
    username: root
    password: rootpw