server:
  port: 8080

springdoc:
  packagesToScan: com.sepacyber.ipgproxy.api


spring:
  redis:
      host: ${REDIS_SERVER:192.168.13.132}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:""}

