server:
  servlet:
    context-path: /


springdoc:
  packagesToScan: com.sepacyber.ipgproxy.api

spring:
  application:
    name: ipg-proxy
  profiles:
    active: dev,swagger

  redis:
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:""}

  config:
    import: optional:configserver:https://sepa-cyber.com/api/production/config
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/ipg_proxy
#    username: ${MARIA_DB_USERNAME:root}
#    password: ${MARIA_DB_PASSWORD:}