server:
  servlet:
    context-path: /


springdoc:
  packagesToScan: com.sepacyber.ipgproxy.api

spring:
  application:
    name: ipg-proxy
  profiles:
    active: dev,swagger

  redis:
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:""}

  config:
    import: optional:configserver:https://sepa-cyber.com/api/production/config
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/ipg_proxy
#    username: root
#    password: rootpw

business:
  service:
    url: ${BUSINESS_MS_API_URL:http://localhost:3000}


application:
  ipg:
    success-response-codes:
      - 200
      - 10004
      - 90026
      - 00008
      - 00009
      - 00002
      - 00024
      - 00003
      - 00025
      - 00022
      - 00001
      - 00023
      - 00006
      - 00028
      - 00007
      - 00029
      - 00004
      - 00026
      - 00005
      - 00027
      - 00020
      - 00019
      - 00013
      - 00035
      - 00014
      - 00011
      - 00012
      - 00034
      - 00017
      - 00018
      - 00015
      - 00016
      - 00031
      - 00010
      - 00030
